export const capitalKoMap = {
    "Seoul": "서울",
    "Tokyo": "도쿄",
    "Beijing": "베이징",
    "Bangkok": "방콕",
    "Paris": "파리",
    "London": "런던",
    "Rome": "로마",
    "Berlin": "베를린",
    "Madrid": "마드리드",
    "Lisbon": "리스본",
    "Vienna": "빈",
    "Prague": "프라하",
    "Amsterdam": "암스테르담",
    "Washington": "워싱턴 D.C.",
    "Ottawa": "오타와",
    "Canberra": "캔버라",
    "Moscow": "모스크바",
    "New Delhi": "뉴델리",
    "Jakarta": "자카르타",
    "Kuala Lumpur": "쿠알라룸푸르",
    "Manila": "마닐라",
    "Taipei": "타이베이",
    "Hanoi": "하노이",
    "Mexico City": "멕시코시티",
    "Brasilia": "브라질리아",
    "Buenos Aires": "부에노스아이레스",
    "Cairo": "카이로",
    "Athens": "아테네",
    "Reykjavik": "레이캬비크",
    "Stockholm": "스톡홀름"
  };
  

  export const koToEnMap = {
    "도쿄": "Tokyo",
    "오사카": "Osaka",
    "교토": "Kyoto",
    "삿포로": "Sapporo",
    "나고야": "Nagoya",
    "후쿠오카": "Fukuoka",
    "오키나와": "Okinawa",
    "히로시마": "Hiroshima",
    "파리": "Paris",
    "리옹": "Lyon",
    "마르세유": "Marseille",
    "니스": "Nice",
    "보르도": "Bordeaux",
    "뉴욕": "New York",
    "로스앤젤레스": "Los Angeles",
    "샌프란시스코": "San Francisco",
    "라스베이거스": "Las Vegas",
    "시카고": "Chicago",
    "마이애미": "Miami",
    "워싱턴 D.C.": "Washington",
    "런던": "London",
    "맨체스터": "Manchester",
    "에딘버러": "Edinburgh",
    "리버풀": "Liverpool",
    "버밍엄": "Birmingham",
    "베를린": "Berlin",
    "뮌헨": "Munich",
    "프랑크푸르트": "Frankfurt",
    "함부르크": "Hamburg",
    "쾰른": "Cologne",
    "로마": "Rome",
    "밀라노": "Milan",
    "피렌체": "Florence",
    "베네치아": "Venice",
    "나폴리": "Naples",
    "마드리드": "Madrid",
    "바르셀로나": "Barcelona",
    "세비야": "Seville",
    "그라나다": "Granada",
    "발렌시아": "Valencia",
    "베이징": "Beijing",
    "상하이": "Shanghai",
    "광저우": "Guangzhou",
    "청두": "Chengdu",
    "시안": "Xi'an",
    "항저우": "Hangzhou",
    "서울": "Seoul",
    "부산": "Busan",
    "제주": "Jeju",
    "대구": "Daegu",
    "광주": "Gwangju",
    "인천": "Incheon"
  };
  