export const capitalKoMap = {
    "Seoul": "서울",
    "Tokyo": "도쿄",
    "Beijing": "베이징",
    "Bangkok": "방콕",
    "Paris": "파리",
    "London": "런던",
    "Rome": "로마",
    "Berlin": "베를린",
    "Madrid": "마드리드",
    "Lisbon": "리스본",
    "Vienna": "빈",
    "Prague": "프라하",
    "Amsterdam": "암스테르담",
    "Washington": "워싱턴 D.C.",
    "Ottawa": "오타와",
    "Canberra": "캔버라",
    "Moscow": "모스크바",
    "New Delhi": "뉴델리",
    "Jakarta": "자카르타",
    "Kuala Lumpur": "쿠알라룸푸르",
    "Manila": "마닐라",
    "Taipei": "타이베이",
    "Hanoi": "하노이",
    "Mexico City": "멕시코시티",
    "Brasilia": "브라질리아",
    "Buenos Aires": "부에노스아이레스",
    "Cairo": "카이로",
    "Athens": "아테네",
    "Reykjavik": "레이캬비크",
    "Stockholm": "스톡홀름"
  };
  